### ISSUE TITLE
Improve PromQL expressions to resist the label change

### ISSUE THREAD

**Issue by chess-knight** [dNationCloud/kubernetes-monitoring#115]
Problem:
- change in PromQL labels, for example in #88 we deleted label **alertGroup**
- [prometheus](https://prometheus.io/docs/practices/naming/#labels) says: "Remember that every unique combination of key-value label pairs represents a new time series"
- we upgraded monitoring and selected time range in grafana that covers both the old and the new version
- in some panels we can see two entries, but in some of them we want to see only one aggregated number

Solution:
- in affected PromQL expressions add aggregation operator, e.g. avg()
- for example this [mysql query](https://github.com/dNationCloud/kubernetes-monitoring/blob/main/jsonnet/dashboards/apps/mysql-exporter.libsonnet#L61) is affected

**Comment by MlsnyLisiak** [comment]
affected queries:
- [ ] rate(mysql_global_status_queries{cluster=~"", job=~"prod-sql-h-1-mysql-exporter", instance=~"116\\.203\\.81\\.200:9104"}[5m])
- [ ] mysql_global_status_uptime{cluster=~"", job=~"prod-sql-h-1-mysql-exporter", instance=~"116\\.203\\.81\\.200:9104"}
- [ ] mysql_global_variables_innodb_buffer_pool_size{cluster=~"", job=~"prod-sql-h-1-mysql-exporter", instance=~"116\\.203\\.81\\.200:9104"}
- [ ] rate(mysql_global_status_questions{cluster=~"", job=~"prod-sql-h-1-mysql-exporter", instance=~"116\\.203\\.81\\.200:9104"}[5m])
- [ ] mysql_global_status_qcache_free_memory{cluster=~"", job=~"prod-sql-h-1-mysql-exporter", instance=~"116\\.203\\.81\\.200:9104"}
- [ ] mysql_global_variables_query_cache_size{cluster=~"", job=~"prod-sql-h-1-mysql-exporter", instance=~"116\\.203\\.81\\.200:9104"}
...

**Comment by MlsnyLisiak** [comment]
Fixed by wrapping existing promQL expressions in avg aggregation like    avg("expression") by (instance)

Future simillar bugs in other dashboards will be fixed "per Issue".
