### ISSUE TITLE
Duplicate series error after alertGroup label deletition

### ISSUE THREAD

**Issue by davidsuba** [dNationCloud/kubernetes-monitoring#117]
After `alertGroup` label was deleted, queries in NodeExporter with `group_left` return error when query span over deployment time.
![image](https://user-images.githubusercontent.com/72123207/121686200-28fb7880-cac1-11eb-8925-3b293ededd60.png)

**Comment by davidsuba** [comment]
Possible duplicate of #115

**Comment by chess-knight** [comment]
Fixed in `node-exporter` dashboard by wrapping right hand-side of *group_left* expressions with `avg by (instance,nodename)`

Future similar bugs in other dashboards will be fixed "per Issue".
