### ISSUE TITLE
MySQL dashboard should have hostname

### ISSUE THREAD

**Issue by rkosegi** [dNationCloud/kubernetes-monitoring#118]
Dashboard introduced [here](https://github.com/dNationCloud/kubernetes-monitoring/issues/70) does not use hostname as `instance` identifier, instead there is endpoint, such as `127.0.0.1:9104`. 
This make it really unusable.

**Comment by matofeder** [comment]
Currently, there is no standard prometheus-operator technique how to scrape external services by its FQDN as is described [here](https://github.com/prometheus-operator/prometheus-operator/issues/3204).
Workaround is to to apply `relabel_configs` which could be done by default values override, see [here ](https://github.com/prometheus-operator/prometheus-operator/issues/3204#issuecomment-847866714)
