### ISSUE TITLE
Color problem: white value on white background

### ISSUE THREAD

**Issue by chess-knight** [dNationCloud/kubernetes-monitoring#129]
If Grafana UI Theme is set to `Light`, **used** and **totalCores**/**RAM**/**Disk** panel values are not visible.

**Comment by davidsuba** [comment]
Example:
![image](https://user-images.githubusercontent.com/72123207/135624930-3dc4a372-efde-4f33-9c04-73e085cc8348.png)
![image](https://user-images.githubusercontent.com/72123207/135625053-d40bee08-b446-46e2-a82a-170041011948.png)

New color has to be defined in [config](https://github.com/dNationCloud/kubernetes-monitoring/blob/main/jsonnet/config.libsonnet) and used in appropriate [templates](https://github.com/dNationCloud/kubernetes-monitoring/blob/main/jsonnet/templates.libsonnet).
