### ISSUE TITLE
Add ci actions to test monitoring installation in latest k8s [releases](https://kubernetes.io/releases/)

### ISSUE THREAD

**Issue by matofeder** [dNationCloud/kubernetes-monitoring#130]

**Comment by davidsuba** [comment]
Because it is time demanding action it shouldn't run on every PR but e.g. once in a month.

**Comment by davidsuba** [comment]
This will be tested only in [kubernetes-monitoring-stack](https://github.com/dNationCloud/kubernetes-monitoring-stack/issues/35) since it always test latest minor version of kuberentes-monitoring chart.
