### ISSUE TITLE
Record short video to show the latest monitoring state.  

### ISSUE THREAD

**Issue by matofeder** [dNationCloud/kubernetes-monitoring#16]
- You can use the same subtitles/sound as in [v1](https://www.youtube.com/watch?v=nrXvRKlsLgs)
- Show drill down from L0 to L3

**Comment by MlsnyLisiak** [comment]
https://drive.google.com/file/d/1UvFXYXqjYepFVzNzkn3YZIh_KH6BIi1g/view
